### ISSUE TITLE
The ZIP file cannot download

### ISSUE THREAD

**Issue by zyhsweety** [lvsn/shadowcompositing#1]
Dear author,
when I try to download the assets, it shows that it cannot be downloaded.
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<BucketName>hdrdb-public</BucketName>
<RequestId>tx0000021b1bc3530b02c2d-0065aba825-29113e76-campusprcc</RequestId>
<HostId>29113e76-campusprcc-ul</HostId>
</Error>`

**Comment by lvrma** [comment]
Ah, I apologize, I'll fix the links asap!

**Comment by nima766** [comment]
Hi, the download link is still not working.

**Comment by lvrma** [comment]
Sorry for the delay! Should be working now.

**Comment by LightwheelAI** [comment]
> Sorry for the delay! Should be working now.

Hi @lvrma , seems these ZIP links are not working again right now. All return 503 error. Please help. Thanks!!!!!!!!!!

<img width="679" alt="image" src="https://github.com/lvsn/shadowcompositing/assets/159144751/0257fe76-1229-475c-b23c-9cf83e1af09e">
