### ISSUE TITLE
ZIP download link unaccessable

### ISSUE THREAD

**Issue by yjmade** [lvsn/shadowcompositing#2]
Dear author,

the checkpoint download linlk you provide in the README is unaccessable, return 503 error, please kindly help to fix it. Thanks!!

<img width="661" alt="image" src="https://github.com/lvsn/shadowcompositing/assets/1754190/cdc895b6-4300-429b-80a7-bbca9140705c">

**Comment by lvrma** [comment]
Strange, all links work fine for me. Can you double-check your local network? What location are you accessing it from? If more people start getting this issue, I will look for a place to upload mirrors.
